CREATE TABLE IF NOT EXISTS users
(
    ID uuid,
    USERNAME VARCHAR NOT NULL UNIQUE,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT 'f',
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS pokemon_cards
(
    ID uuid,
    TYPE_ITEM VARCHAR NOT NULL,
    KEYTAG VARCHAR NOT NULL,
    PRODUCT_STATE VARCHAR NOT NULL,
    LANG_EDITION VARCHAR NOT NULL,
    SUBCOLLECTION VARCHAR NOT NULL,
    COLLECTION_NAME VARCHAR NOT NULL,
    COLLECTION_STR_ID VARCHAR NOT NULL,
    POKEMON_STR_ID VARCHAR NOT NULL,
    POKEMON_DESCRIPTION VARCHAR NOT NULL UNIQUE,
    IS_AVAILABLE BOOLEAN NOT NULL DEFAULT 't',
    PRIMARY KEY (ID)
);

-- COPY pokemon_cards(ID, TYPE_ITEM, KEYTAG, PRODUCT_STATE, LANG_EDITION, SUBCOLLECTION, COLLECTION_NAME, COLLECTION_STR_ID, POKEMON_STR_ID, POKEMON_DESCRIPTION)
-- FROM '/tmp/pokemon_list.csv'
-- DELIMITER ';'
-- CSV HEADER;
